### ISSUE TITLE
Compilation errors. 

### ISSUE THREAD

**Issue by josancardenasm** [Lupus/ccl#1]
Hi, i'm trying to compile this library in cygwin. 
i'm trying next : 
```
mkdir build
cd build
cmake ..
make
```

and i'm getting nex error message from make 
```
ccl/dlist.c: In function ‘AddRange’:
ccl/dlist.c:296:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
  296 |     if (AL->Flags & CONTAINER_HAS_OBSERVER)
      |     ^~
ccl/dlist.c:299:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  299 |         return 1;
      |         ^~~~~~
cc1: all warnings being treated as errors
```
I have tried also in Ubuntu and i get the same result.

**Comment by josancardenasm** [comment]
Hi, i'm trying to compile this library in cygwin. 
i'm trying next : 
`mkdir build
cd build
cmake ..
make`

and i'm getting nex error message from make 
`
ccl/dlist.c: In function ‘AddRange’:
ccl/dlist.c:296:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
  296 |     if (AL->Flags & CONTAINER_HAS_OBSERVER)
      |     ^~
ccl/dlist.c:299:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  299 |         return 1;
      |         ^~~~~~
cc1: all warnings being treated as errors
`

**Comment by Lupus** [comment]
Hi, I've mirrored this library on Github long time ago as source did not seem reliable. Tried building it and abandoned this effort, so I can't really help, sorry.

**Comment by Lupus** [comment]
It seems that the author has moved to Github: https://github.com/jacob-navia/ccl
Makes sense to try that version and repost your question if it still applies.
